baseURL = 'https://isaiah.bloyer.net/'
languageCode = 'en-us'
title = 'Isaiah (Ike) Bloyer'

[params]
github = 'https://github.com/ike2117/'
linkedin = 'https://www.linkedin.com/in/isaiah-bloyer-969958248/'
email = "isaiah@bloyer.net"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

[module]
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

disableKinds = ["taxonomy"]